version: '3.7'

services:
  public:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${BENTO_PUBLIC_IMAGE}:${BENTO_PUBLIC_VERSION}
    container_name: ${BENTO_PUBLIC_CONTAINER_NAME}
    networks: 
      - bridge-net
    environment:
      - BENTO_PUBLIC_KATSU_URL=${BENTO_PUBLIC_KATSU_URL}
      - BENTO_PUBLIC_MAX_QUERY_PARAMETERS=${BENTO_PUBLIC_MAX_QUERY_PARAMETERS}
      - BENTO_PUBLIC_PORTAL_URL=${BENTO_PUBLIC_PORTAL_URL}
    expose:
      - "${BENTO_PUBLIC_INTERNAL_PORT}"

networks: 
  bridge-net:
    external: true