export const API_PROJECTS = {
  count: 5,
  next: null,
  previous: null,
  results: [
    {
      identifier: '1cf7fde3-2a2f-42df-9804-d1e46ac7e440',
      discovery: null,
      datasets: [
        {
          language: 'en',
          schema_version: '1.0',
          title: 'Apis Florea',
          description: 'Wild Honey Bee',
          long_description: null,
          taxa: null,
          keywords: null,
          resources: null,
          stakeholders: null,
          funding_sources: null,
          spatial_coverage: null,
          version: '1.o',
          privacy: null,
          license: null,
          counts: null,
          primary_contact: {
            type: 'organization',
            name: 'RefSec',
            description: null,
            contact: null,
            location: null,
            roles: ['Other'],
          },
          links: null,
          publications: null,
          logos: null,
          release_date: null,
          last_modified: null,
          participant_criteria: null,
          study_status: null,
          study_context: null,
          domain: null,
          program_name: null,
          pcgl_dac_id: null,
          discovery: null,
          extra_properties: null,
          identifier: '33e61b2e-d753-4cae-8902-a502992a8637',
          project: '1cf7fde3-2a2f-42df-9804-d1e46ac7e440',
          linked_field_sets: [],
          created_at: '2026-07-21T22:42:01.128450Z',
          updated_at: '2026-07-21T22:42:01.128465Z',
          counts_by_entity: { experiment_result: 0, phenopacket: 0, individual: 0, experiment: 0, biosample: 0 },
          translations: [],
        },
      ],
      project_schemas: [],
      counts: { experiment_result: 0, phenopacket: 0, individual: 0, experiment: 0, biosample: 0 },
      created: '2026-07-21T22:44:57.904106Z',
      updated: '2026-07-21T22:16:53.802224Z',
      title: 'Data Proyect',
      description: 'A nice project',
    },
    {
      identifier: '222d719a-d46a-49b3-af95-25e76036dce8',
      discovery: null,
      datasets: [
        {
          language: 'en',
          schema_version: '1.0',
          title: 'NCBITaxon9606',
          description: 'Homo sapiens',
          long_description: null,
          taxa: null,
          keywords: [
            'aberrant splicing',
            'Cardiovascular Disease',
            'metabolomics',
            'wearable sensors',
            'Rare Disease',
            'undiagnosed disease',
          ],
          resources: null,
          stakeholders: null,
          funding_sources: null,
          spatial_coverage: null,
          version: '1.0',
          privacy: null,
          license: null,
          counts: null,
          primary_contact: {
            type: 'organization',
            name: 'McGill0020',
            description: null,
            contact: null,
            location: null,
            roles: ['Other'],
          },
          links: null,
          publications: null,
          logos: null,
          release_date: null,
          last_modified: null,
          participant_criteria: null,
          study_status: null,
          study_context: null,
          domain: null,
          program_name: null,
          pcgl_dac_id: null,
          discovery: null,
          extra_properties: null,
          identifier: '7ae562fe-f05e-4044-81f2-20dbde663943',
          project: '222d719a-d46a-49b3-af95-25e76036dce8',
          linked_field_sets: [],
          created_at: '2026-07-21T17:24:01.650239Z',
          updated_at: '2026-08-04T18:43:03.653569Z',
          counts_by_entity: {
            experiment_result: 4236,
            phenopacket: 2606,
            individual: 2606,
            experiment: 4101,
            biosample: 4949,
          },
          translations: [],
        },
      ],
      project_schemas: [],
      counts: { experiment_result: 4236, phenopacket: 2606, individual: 2606, experiment: 4101, biosample: 4949 },
      created: '2026-07-21T17:19:22.131687Z',
      updated: '2026-07-21T17:19:22.131724Z',
      title: 'My Health Data Project',
      description: 'Awesome project',
    },
    {
      identifier: '44d374b6-6bf2-4f4a-9b59-088d0bae5f2d',
      discovery: null,
      datasets: [
        {
          language: 'en',
          schema_version: '1.0',
          title: 'NCBI Taxon 63221',
          description: 'Homo sapiens neanderthalensis ',
          long_description: null,
          taxa: null,
          keywords: null,
          resources: null,
          stakeholders: null,
          funding_sources: null,
          spatial_coverage: null,
          version: null,
          privacy: null,
          license: null,
          counts: null,
          primary_contact: {
            type: 'person',
            name: 'Jose Garcia',
            honorific: null,
            other_names: null,
            affiliations: null,
            contact: null,
            location: null,
            orcid: null,
            roles: ['Other'],
          },
          links: null,
          publications: null,
          logos: null,
          release_date: null,
          last_modified: null,
          participant_criteria: null,
          study_status: null,
          study_context: null,
          domain: null,
          program_name: null,
          pcgl_dac_id: null,
          discovery: null,
          extra_properties: null,
          identifier: '46d7c1ab-a875-43d7-883f-5281fbb1987c',
          project: '44d374b6-6bf2-4f4a-9b59-088d0bae5f2d',
          linked_field_sets: [],
          created_at: '2026-08-04T18:31:24.431736Z',
          updated_at: '2026-08-04T18:31:24.431749Z',
          counts_by_entity: { experiment_result: 0, phenopacket: 0, individual: 0, experiment: 0, biosample: 0 },
          translations: [],
        },
      ],
      project_schemas: [],
      counts: { experiment_result: 0, phenopacket: 0, individual: 0, experiment: 0, biosample: 0 },
      created: '2026-08-04T18:25:30.267097Z',
      updated: '2026-08-04T18:25:30.267122Z',
      title: 'BioForge',
      description: 'Creating artificial cellular scaffolds to grow functional transplant organs.',
    },
    {
      identifier: 'b0e2a169-e28d-4cf5-a394-a41b7cf86ed0',
      discovery: null,
      datasets: [
        {
          language: 'en',
          schema_version: '1.0',
          title: 'NCBITaxon9606',
          description: 'Human (Homo sapiens) is a species of primate in the family Hominidae',
          long_description: null,
          taxa: null,
          keywords: null,
          resources: null,
          stakeholders: null,
          funding_sources: null,
          spatial_coverage: null,
          version: null,
          privacy: null,
          license: null,
          counts: null,
          primary_contact: {
            type: 'person',
            name: 'Jose Garcia',
            honorific: null,
            other_names: null,
            affiliations: null,
            contact: null,
            location: null,
            orcid: null,
            roles: ['Other'],
          },
          links: null,
          publications: null,
          logos: null,
          release_date: null,
          last_modified: null,
          participant_criteria: null,
          study_status: null,
          study_context: null,
          domain: null,
          program_name: null,
          pcgl_dac_id: null,
          discovery: null,
          extra_properties: null,
          identifier: '8f8131d7-3227-49ba-8945-07640174ed10',
          project: 'b0e2a169-e28d-4cf5-a394-a41b7cf86ed0',
          linked_field_sets: [],
          created_at: '2026-08-04T18:29:45.005595Z',
          updated_at: '2026-08-04T18:29:45.005608Z',
          counts_by_entity: { experiment_result: 0, phenopacket: 0, individual: 0, experiment: 0, biosample: 0 },
          translations: [],
        },
      ],
      project_schemas: [],
      counts: { experiment_result: 0, phenopacket: 0, individual: 0, experiment: 0, biosample: 0 },
      created: '2026-08-04T18:25:07.661522Z',
      updated: '2026-08-04T18:25:07.661547Z',
      title: 'Project Helix Craft',
      description: 'Engineering custom synthetic DNA strands to address hereditary medical conditions.',
    },
    {
      identifier: 'b68ed466-4f05-48af-8741-3dff5d3c06b8',
      discovery: null,
      datasets: [
        {
          language: 'en',
          schema_version: '1.0',
          title: 'Apis Florea',
          description: 'Wild Honey Bee\n',
          long_description: null,
          taxa: null,
          keywords: null,
          resources: null,
          stakeholders: null,
          funding_sources: null,
          spatial_coverage: null,
          version: null,
          privacy: null,
          license: null,
          counts: null,
          primary_contact: {
            type: 'person',
            name: 'Jose Garcia',
            honorific: null,
            other_names: null,
            affiliations: null,
            contact: null,
            location: null,
            orcid: null,
            roles: ['Other'],
          },
          links: null,
          publications: null,
          logos: null,
          release_date: null,
          last_modified: null,
          participant_criteria: null,
          study_status: null,
          study_context: null,
          domain: null,
          program_name: null,
          pcgl_dac_id: null,
          discovery: null,
          extra_properties: null,
          identifier: '1550c7e3-46c0-495b-89f5-38718fec38cd',
          project: 'b68ed466-4f05-48af-8741-3dff5d3c06b8',
          linked_field_sets: [],
          created_at: '2026-08-04T18:27:43.961977Z',
          updated_at: '2026-08-04T18:27:43.961994Z',
          counts_by_entity: { experiment_result: 0, phenopacket: 0, individual: 0, experiment: 0, biosample: 0 },
          translations: [],
        },
      ],
      project_schemas: [],
      counts: { experiment_result: 0, phenopacket: 0, individual: 0, experiment: 0, biosample: 0 },
      created: '2026-08-04T18:25:55.319693Z',
      updated: '2026-08-04T18:25:55.319710Z',
      title: 'Project Proteus',
      description: 'Rewriting protein-folding instructions to target and dissolve cancerous tumors.',
    },
  ],
};
