name: Build and push bento_public

on:
  release:
    types: [ published ]
  pull_request:
    branches:
      - main
      - features/**
      - feat/**
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run Bento build action
        uses: bento-platform/bento_build_action@v1.0.0
        with:
          registry: ghcr.io
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          image-name: ghcr.io/bento-platform/bento_public
          development-dockerfile: dev.Dockerfile
          dockerfile: Dockerfile
