name: Build and push bento_public

# on:
#   release:
#     types: [ published ]
#   pull_request:
#     branches:
#       - master
#   push:
#     branches:
#       - master

# on: workflow_dispatch

on:
  push:
    branches:
      - "testing-build"

jobs:
  build-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into the container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Set up development image metadata
        id: meta-dev
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/bento-platform/bento_beacon
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest-dev,enable={{is_default_branch}}
            type=ref,event=pr
            type=sha,prefix=sha-

      - name: Build and push development image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: dev.Dockerfile
          push: true
          tags: ${{ steps.meta-dev.outputs.tags }}
          labels: ${{ steps.meta-dev.outputs.labels }}
          platforms: linux/amd64,linux/arm64
