name: Lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install modules
        run: npm install
      - name: Run eslint + prettier plugin
        run: npm run lint
